name: Build and Deploy to Existing GKE

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # REQUIRED for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ðŸ”‘ REQUIRED for modern GKE authentication
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: "True"

    steps:
    # ----------------------------
    # Checkout source code
    # ----------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # ----------------------------
    # Authenticate to GCP using OIDC
    # ----------------------------
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/881925804294/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-gke-sa@pooja31.iam.gserviceaccount.com

    # ----------------------------
    # Setup gcloud CLI
    # ----------------------------
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    # ----------------------------
    # Install GKE auth plugin (MANDATORY)
    # ----------------------------
    - name: Install GKE gcloud auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    # ----------------------------
    # Configure Docker for Artifact Registry
    # ----------------------------
    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    # ----------------------------
    # Build & Push Docker Image
    # ----------------------------
    - name: Build and Push Image
      run: |
        docker build -t asia-south1-docker.pkg.dev/pooja31/backend-repo/backend-app:latest .
        docker push asia-south1-docker.pkg.dev/pooja31/backend-repo/backend-app:latest

    # ----------------------------
    # Get GKE credentials (ZONAL CLUSTER)
    # ----------------------------
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials secure-gke \
          --zone asia-south1-a \
          --project pooja31

    # ----------------------------
    # Deploy to GKE
    # ----------------------------
    - name: Deploy to Kubernetes
      run: |
       
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
